Implemented Auth and Player

diff --git a/lib/libspotify-cli/auth/authorize b/lib/libspotify-cli/auth/authorize
--- a/lib/libspotify-cli/auth/authorize
+++ b/lib/libspotify-cli/auth/authorize
@@ -1,28 +1,52 @@
 #!/bin/bash
 # vim: ft=bash ts=2 sw=2 et ff=unix fenc=utf-8
 
-set -u
-
 # Part of Spotify-cli
 # Authorization Code Flow with Proof Key for Code Exchange (PKCE)
 
-CONFDIR="../config"
-source ${CONFDIR}/basic_settings
+set -eu
 
+##### Load libraries
+_CURDIR="$(cd $(dirname $0) ; pwd)"
+LIBSPDIR=${LIBSPDIR:="${_CURDIR}/.."}     # (Caution) varies according to _CURDIR
+CONFDIR=${CONFIDR:="${LIBSPDIR}/config"}
+source ${CONFDIR}/basic_settings
+source ${COMMONDIR}/http_status
+
+##### API
 URLBASE="https://accounts.spotify.com"
 API="authorize"
 
+##### Processing body
+function get_verifier {
+  dd bs=64 count=1 if=/dev/urandom 2>/dev/null \
+    | base64 -w 1024 \
+    | sed -e 's/+/-/g;' -e 's/\//_/g' -e 's/=//g'
+}
+
+function get_challenge {
+  printf "${CODE_VERIFIER}" \
+    | openssl sha256 -binary \
+    | base64 -w 1024 \
+    | sed -e 's/+/-/g;' -e 's/\//_/g' -e 's/=//g'
+}
+
+function get_state {
+  dd bs=64 count=1 if=/dev/urandom 2>/dev/null \
+    | sha256sum \
+    | cut -c-12
+}
+
 RESPONSE_TYPE=code
-REDIRECT_URI="http://localhost:1234/callback_gen.php"
 SCOPE="${SCOPE_ALL}"
 CODE_CHALLENGE_METHOD="S256"
-CODE_VERIFIER=$(dd bs=64 count=1 if=/dev/urandom 2>/dev/null | base64 -w 1024 | sed -e 's/+/-/g;' -e 's/\//_/g' -e 's/=//g')
-CODE_CHALLENGE=$(echo -n ${CODE_VERIFIER} | openssl sha256 -binary | base64 -w 1024 | sed -e 's/+/-/g;' -e 's/\//_/g' -e 's/=//g')
-STATE=$(dd bs=64 count=1 if=/dev/urandom 2>/dev/null | sha256sum | cut -c-12)
+CODE_VERIFIER=$(get_verifier)
+CODE_CHALLENGE=$(get_challenge)
+STATE=$(get_state)
 
-echo -n ${CODE_VERIFIER} > ${CONFDIR}/code_verifier
-echo -n ${CODE_CHALLENGE} > ${CONFDIR}/code_challenge
-echo -n ${STATE} > ${CONFDIR}/state
+printf "${CODE_VERIFIER}" > ${CONFDIR}/code_verifier
+printf "${CODE_CHALLENGE}" > ${CONFDIR}/code_challenge
+printf "${STATE}" > ${CONFDIR}/state
 
 # curl ${1:-} -s -k -G \
 #   -i \
@@ -38,6 +62,13 @@ echo -n ${STATE} > ${CONFDIR}/state
 #
 # exit 16
 
+# Invoke webserver for callback
+while [ -z ${SERVER_PID:=$(lsof -t -i:${REDIRECT_PORT} || true)} ]
+do
+  ${AUTHDIR}/callback/php/invoke_server.sh ${REDIRECT_PORT} "${AUTHDIR}/callback/php" &> /dev/null
+  sleep 2
+done
+
 RESPONSE=$(curl ${1:-} -s -k -G -o /dev/null \
   --write-out '%{http_code} %{size_header} %{redirect_url}' \
   --header "${HEADER_ALWAYS}" \
@@ -51,9 +82,22 @@ RESPONSE=$(curl ${1:-} -s -k -G -o /dev/null \
   "${URLBASE}/${API}"
 )
 
-#HEADERS=$(sed -n '1,/^\r$/p' <<< "${RESPONSE}")
-#CONTENT=$(sed -e '1,/^\r$/d' -e '$d' <<< "${RESPONSE}")
+read -r HTTP_CODE SIZE_HEADER REDIRECT_URL <<< "${RESPONSE}"
 
-read -r http_code size_header redirect_url <<< "${RESPONSE}"
-echo "${redirect_url}"
+# Error check
+if [ $(IS_HTTP_REDIRECT "${HTTP_CODE}") = "${S_FALSE}" ]; then
+  #echo "Something wrong!(HTTP Status Code: ${HTTP_CODE})"
+  echo "${R_PREFIX}:${R_FAIL}:${HTTP_CODE}"
+  exit ${HTTP_CODE}
+fi 1>&2
+
+# Normal output
+if [ -z "${URL_OPENER}" ]; then
+  echo "${REDIRECT_URL}"
+else
+  ${URL_OPENER} ${REDIRECT_URL}
+fi
+
+echo "${R_PREFIX}:${R_SUCCESS}:${HTTP_CODE}" 1>&2
+exit 0
 
diff --git a/lib/libspotify-cli/auth/refresh b/lib/libspotify-cli/auth/refresh
--- a/lib/libspotify-cli/auth/refresh
+++ b/lib/libspotify-cli/auth/refresh
@@ -5,7 +5,7 @@ set -eu
 
 # Part of Spotify-cli
 # Authorization Code Flow with Proof Key for Code Exchange (PKCE)
-# Exchange authorization code to access token.
+# Requesting a refreshed access token
 
 ##### Load libraries
 _CURDIR="$(cd $(dirname $0) ; pwd)"
@@ -20,17 +20,30 @@ URLBASE="https://accounts.spotify.com"
 API="api/token"
 
 ##### Processing body
-GRANT_TYPE="authorization_code"
-CODE="$(<${CONFDIR}/authorization_code)"
-CODE_VERIFIER="$(<${CONFDIR}/code_verifier)"
+GRANT_TYPE="refresh_token"
+REFRESH_TOKEN="$(<${CONFDIR}/refresh_token)"
+if [ -z "${REFRESH_TOKEN}"  ]; then
+  echo "${R_PREFIX}:${R_UNAUTH}:${HTTP_UNAUTHORIZED}" 1>&2
+  exit ${HTTP_UNAUTHORIZED}
+fi
+TOKEN_EPOCH="$(<${CONFDIR}/token_epoch)"
+if [ -z "${TOKEN_EPOCH}"  ]; then
+  echo "${R_PREFIX}:${R_UNAUTH}:${HTTP_UNAUTHORIZED}" 1>&2
+  exit ${HTTP_UNAUTHORIZED}
+fi
+
+CURRENT_EPOCH="$(get_epoch)"
+echo "Duration: $((${CURRENT_EPOCH} - ${TOKEN_EPOCH})) " > ${CONFDIR}/duration
+if [ $((${CURRENT_EPOCH} - ${TOKEN_EPOCH})) -le 3540 ]; then
+  echo "${R_PREFIX}:${R_SUCCESS}:${HTTP_OK}" 1>&2
+  exit 0
+fi
 
 # curl ${1:-} --silent --insecure --write-out '\n\n%{http_code}\n' \
 #   --header "${HEADER_ALWAYS}" \
 #   --data-urlencode "client_id=${CLIENT_ID}" \
 #   --data-urlencode "grant_type=${GRANT_TYPE}" \
-#   --data-urlencode "code=${CODE}" \
-#   --data-urlencode "redirect_uri=${REDIRECT_URI}" \
-#   --data-urlencode "code_verifier=${CODE_VERIFIER}" \
+#   --data-urlencode "refresh_token=${REFRESH_TOKEN}" \
 #   "${URLBASE}/${API}"
 #
 # exit 16
@@ -39,29 +52,18 @@ RESPONSE=$(curl ${1:-} --silent --insecure --write-out '\n\n%{http_code}\n' \
   --header "${HEADER_ALWAYS}" \
   --data-urlencode "client_id=${CLIENT_ID}" \
   --data-urlencode "grant_type=${GRANT_TYPE}" \
-  --data-urlencode "code=${CODE}" \
-  --data-urlencode "redirect_uri=${REDIRECT_URI}" \
-  --data-urlencode "code_verifier=${CODE_VERIFIER}" \
+  --data-urlencode "refresh_token=${REFRESH_TOKEN}" \
   "${URLBASE}/${API}"
 )
 
 HTTP_CODE=$(tail -n1 <<< "${RESPONSE}")
 RES_BODY=$(head -n-1 <<< "${RESPONSE}")
 
-# Stop server for callback
-until [ -z ${SERVER_PID:=$(lsof -t -i:${REDIRECT_PORT} || true)} ]
-do
-   kill ${SERVER_PID}
-   sleep 1
-   SERVER_PID=$(lsof -t -i:${REDIRECT_PORT} || true)
-done
-
-# HTTP Error check
+# Error check
 if [ "${HTTP_CODE}" -ne "${HTTP_OK}" ]; then
-  #echo "Something wrong!(HTTP Status Code: ${HTTP_CODE})"
-  echo "${R_PREFIX}:${R_FAIL}:${HTTP_CODE}"
+  echo "${R_PREFIX}:${R_FAIL}:${HTTP_CODE}" 1>&2
   exit ${HTTP_CODE}
-fi 1>&2
+fi
 
 # Output
 ACCESS_TOKEN=$(echo ${RES_BODY} | jq -r '.access_token')
@@ -69,9 +71,9 @@ REFRESH_TOKEN=$(echo ${RES_BODY} | jq -r '.refresh_token')
 
 # JSON error check
 if [ -z "${ACCESS_TOKEN}" -o -z "${REFRESH_TOKEN}" ]; then
-  echo "${R_PREFIX}:${R_JSON}:${HTTP_UNAUTHORIZED}"
+  echo "${R_PREFIX}:${R_JSON}:${HTTP_UNAUTHORIZED}" 1>&2
   exit ${HTTP_UNAUTHORIZED}
-fi 1>&2
+fi
 
 # Success
 echo $(get_epoch) > ${CONFDIR}/token_epoch
@@ -80,3 +82,4 @@ echo -n "${REFRESH_TOKEN}" > ${CONFDIR}/refresh_token
 
 echo "${R_PREFIX}:${R_SUCCESS}:${HTTP_CODE}" 1>&2
 exit 0
+
diff --git a/lib/libspotify-cli/config/basic_settings b/lib/libspotify-cli/config/basic_settings
--- a/lib/libspotify-cli/config/basic_settings
+++ b/lib/libspotify-cli/config/basic_settings
@@ -1,5 +1,68 @@
+#!/bin/bash
 # vim: ft=bash ts=2 sw=2 et ff=unix fenc=utf-8
 
+# Part of spotify-cli
+# basic_settings
+# ORIGIN: 2020-12-14 by hmr
+
+set -eu
+
+##### System dependent settings
+_SYSTEM=$(uname -s | tr "[A-Z]" "[a-z]")
+case "${_SYSTEM}" in
+  "darwin" )
+    URL_OPENER="open"
+    ;;
+
+  "linux" )
+    URL_OPENER=""
+    ;;
+esac
+
+##### System independent settings
+# Authorization redirect URL
+REDIRECT_PORT="${REDIRECT_PORT:=1234}"
+REDIRECT_URI="http://localhost:${REDIRECT_PORT}/callback_gen.php"
+
+# Directories
+LIBSPDIR="${LIBSPDIR:=~/src/spotify-cli/lib/libspotify-cli}"
+
+ALBUMSDIR="${ALBUMSDIR:=${LIBSPDIR}/albims}"
+ARTISTSDIR="${ARTISTSDIR:=${LIBSPDIR}/artists}"
+AUTHDIR="${AUTHDIR:=${LIBSPDIR}/auth}"
+BROWSEDIR="${BROWSEDIR:=${LIBSPDIR}/browse}"
+COMMONDIR="${COMMONDIR:=${LIBSPDIR}/common}"
+CONFIGDIR="${CONFIGDIR:=${LIBSPDIR}/config}"
+EPISODESDIR="${EPISODESDIR:=${LIBSPDIR}/episodes}"
+FOLLOWDIR="${FOLLOWDIR:=${LIBSPDIR}/follow}"
+LIBRARYDIR="${LIBRARYDIR:=${LIBSPDIR}/library}"
+PERSONALIZATIONDIR="${PERSONALIZATIONDIR:=${LIBSPDIR}/personalization}"
+PLAYLISTSDIR="${PLAYLISTSDIR:=${LIBSPDIR}/playlists}"
+SEARCHDIR="${SEARCHDIR:=${LIBSPDIR}/search}"
+SHOWSDIR="${SHOWSDIR:=${LIBSPDIR}/shows}"
+TRACKSDIR="${TRACKSDIR:=${LIBSPDIR}/tracks}"
+USERSPROFILEDIR="${USERPROFILEDIR:=${LIBSPDIR}/userprofile}"
+PLAYERDIR="${PLAYERDIR:=${LIBSPDIR}/player}"
+
+# Client ID: Don't change
+CLIENT_ID="5dda0289718a42fe8411b26d2d376127"
+
+# HTTP header
+HEADER_ALWAYS="Cache-Control: no-cache"
+
+# Status code
+S_TRUE='true'
+S_FALSE='false'
+
+# Return code/string
+R_PREFIX="libsc"
+R_SUCCESS="success"
+R_FAIL="fail"
+R_ARG="arg"
+R_UNAUTH="unauth"
+R_JSON="json"
+
+##### Scope [https://developer.spotify.com/documentation/general/guides/scopes/]
 # Images
 # * ugc-image-upload
 # Listening History
@@ -21,6 +84,61 @@ SCOPE_ALL="ugc-image-upload user-read-recently-played user-top-read user-read-pl
 SCOPE_PLAY="user-read-currently-playing user-read-playback-state user-modify-playback-state"
 SCOPE_PRIVATE="user-read-email user-read-private"
 
-HEADER_ALWAYS="Cache-Control: no-cache"
-CLIENT_ID="5dda0289718a42fe8411b26d2d376127"
+#
+function get_epoch {
+  date "+%s"
+  return 0
+}
+
+##### Below will be divided to independent file
+# Global option handling
+function getoptions {
+  OPT_REMAIN=()
+  while [ $# -gt 0  ]; do
+    local opt=$1
+    case "${opt}" in
+      "-dd" | "--more-debug" )
+        OPT_DEBUG=1
+        OPT_MORE_DEBUG=1
+        ;;
+
+      "-d" | "--debug" )
+        OPT_DEBUG=1
+        ;;
+
+      * )
+        OPT_REMAIN+="${opt}"
+        ;;
+
+    esac
+    shift
+  done
+}
+
+# Debug line
+function dline {
+  [ -z ${OPT_DEBUG:=""} ] && return 0
+  dprintf "============================================================"
+  return
+}
+
+function dline2 {
+  [ -z ${OPT_DEBUG:=""} ] && return 0
+  dprintf "------------------------------------------------------------"
+  return
+}
+
+# Debug print
+function dprintf {
+  [ -z ${OPT_DEBUG:=""} ] && return 0
+  echo "$@" 1>&2
+  return
+}
+
+# Debug print 2
+function dprintf2 {
+  [ -z ${OPT_DEBUG} ] || [ -z ${OPT_MORE_DEBUG:=""} ] && return 0
+  dprintf "$@"
+  return
+}
 
